### ISSUE TITLE
Set Up and Configure a Cloud Environment in Google Cloud Task 3

### ISSUE THREAD

**Issue by shandytp** [elmoallistair/qwiklabs#10]
Halo selamat malam mas, itu ada kesalahan di Task 3 bagian _create second firewall rule_. Yang dibagian network itu harusnya `griffin-prod-vpc`, bukan `griffin-dev-vpc`.

Terima kasih.

**Comment by elmoallistair** [comment]
oke, sy cek

**Comment by elmoallistair** [comment]
oke sudah dicek dan diupdate 93d5180
