### ISSUE TITLE
Set up and Configure a Cloud Environment in Google Cloud: Challenge Lab 

### ISSUE THREAD

**Issue by effendid** [elmoallistair/qwiklabs#42]
Line 95
--   Replace <username_goes_here> to   **wp-user** 
++ Replace <username_goes_here> to **wp_user**

**Comment by elmoallistair** [comment]
nice found, can you pull request?

**Comment by elmoallistair** [comment]
merged #43 f096563a39297267d061c7d8e7e51ab2d2461686
