### ISSUE TITLE
Add a line that the Tasks have to be done in order

### ISSUE THREAD

**Issue by anandshivam44** [elmoallistair/qwiklabs#50]
Add a line that the Tasks have to be done in order. I tried doing 1 and then 4 first. Assessment failed!
Then I tried doing 2 and then 3. Assessment failed!
It is mandatory to do them in order

**Comment by elmoallistair** [comment]
Which lab? DevOps implementation?

**Comment by anandshivam44** [comment]
Getting Started: Create and Manage Cloud Resources: Challenge Lab
https://google.qwiklabs.com/focuses/10258?parent=catalog

Although all 4 tasks seem unrelatable
still you need to complete then in order

**Comment by elmoallistair** [comment]
We don't have [lab guide](https://github.com/elmoallistair/qwiklabs/tree/master/labs) with that name, did you send the right link/lab name?
