### ISSUE TITLE
change in code

### ISSUE THREAD

**Issue by abhishekd004** [elmoallistair/qwiklabs#66]
replace "location" to "address".

**Comment by elmoallistair** [comment]
hi, can you provide details of the problem?

**Comment by abhishekd004** [comment]
I guess, GCP update the datasets. so, in your code (line 16 and 74 in Github) there is a column name as "location" it should be replaced with "address"

**Comment by elmoallistair** [comment]
Which lab?

**Comment by abhishekd004** [comment]
Create ML Models with BigQuery ML: Challenge Lab

**Comment by elmoallistair** [comment]
are you referring to the [GSP341](https://www.qwiklabs.com/focuses/14294?parent=catalog)? unfortunately we haven't create the guide yet.

**Comment by abhishekd004** [comment]
ok and sorry 
i am closing this issue
