### ISSUE TITLE
need more command to handle error  request resource not found  for GSP #314

### ISSUE THREAD

**Issue by djkampus** [elmoallistair/qwiklabs#67]
after creating kubernetes cluster need to get credential of kraken-prod 

##command to add##
gcloud container clusters get-credentials kraken-prod --zone us-east1-b --project <PROJECT_ID>

**Comment by djkampus** [comment]
> 
> 
> Hi, can you name the lab?

GCP 314 Deploy and Manage Cloud Environments with Google Cloud: Challenge Lab

**Comment by elmoallistair** [comment]
i have reviewed the lab and updated the guide file, thanks!
e0a57a3
