### ISSUE TITLE
Perform Foundational Data, ML, and AI Tasks in Google Cloud Task 4

### ISSUE THREAD

**Issue by TjandraD** [elmoallistair/qwiklabs#9]
Halo mas, saya kemarin nemu problem pas bagian task 4 di challenge labnya. Dan beberapa update di tempat lain bilang kalo GCP kayanya ada minor update buat lab yang satu itu.

**Comment by elmoallistair** [comment]
iyap, banyak korban. coba selesaikan task pake instruksi dari lab sebelumnya --bukan script mentahan dari web. kalo ada waktu sy coba retake

**Comment by elmoallistair** [comment]
resolved ya https://github.com/elmoallistair/qwiklabs/tree/master/perform-foundation-data-ml-and-ai-task-challenge-lab --liat juga https://t.me/JuaraGCP/77313
